- alias: Alert that off-peak electricty hours are just about to start
  trigger:
    platform: time
    at: '12:20:00'
  action:
    - service: notify.all
      data:
        message: 'Midday off-peak hours are from 12:30 - 15:30'
        title: 'Off-Peak hours are about to start'    

- alias: Remind to put on dishwasher or washing machine for off peak hours
  trigger:
    platform: time
    at: '21:00:00'
  action:
    - service: notify.eamonn
      data:
        message: 'Need to put on dishwasher or washing machine? Off-peak night hours from 02:00 - 07:00'
        title: 'Washing Tonight?'

# When we detect power being drawn from the dishwasher,
# mark the dishwasher as using power

- alias: Set dishwasher active when power detected
  trigger:
    - platform: numeric_state
      entity_id: sensor.dishwasher_power
      above: 10
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Dirty
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Clean
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Drying
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dishwasher_status
        option: Running

# When the power level drops below 10, and the Dishwasher is set to
# the 'Running' state, mark the Dishwasher as Finished

- alias: Set dishwasher drying when power drops
  trigger:
    - platform: numeric_state
      entity_id: sensor.dishwasher_power
      below: 10
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Running
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dishwasher_status
        option: Drying

# Once the dishwasher status has been 'Drying' for 30 minutes, mark the
# dishwasher as clean

- alias: Set dishwasher clean
  trigger:
    - platform: state
      entity_id: input_select.dishwasher_status
      to: Drying
      for:
        minutes: 15
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Drying
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dishwasher_status
        option: Clean

# When the power drops and the dishwasher is Clean or Drying, someone has
# turned the Dishwasher off and emptied it. We should do this when the state
# of the Dishwasher is clean or Finishing, just incase someone opens the
# Dishwasher before the 30 minute timeout has been reached.

- alias: Set Dishwasher dirty when power off
  trigger:
    - platform: numeric_state
      entity_id: sensor.dishwasher_power
      below: 0.1
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.dishwasher_power
        below: 1
      - condition: or
        conditions:
        - condition: state
          entity_id: input_select.dishwasher_status
          state: Clean
        - condition: state
          entity_id: input_select.dishwasher_status
          state: Drying
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dishwasher_status
        option: Dirty

- alias: Send alert when dishwasher is clean
  trigger:
    - platform: state
      entity_id: input_select.dishwasher_status
      to: Clean
    - platform: time
      at: '08:30:00'
  condition:
    condition: and
    conditions:
      - condition: time
        before: '22:30:00'
        after: '08:29:00'
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Clean
  action:
    - service: notify.eamonn
      data:
        message: 'The Dishwasher has finished and is ready to be emptied!'
        title: 'Dishwasher Update'

# When power is detected, and the washing machine is not in
# the Running state, change the status of the washing machine
# to Running.
# The status check will ensure we don't try to put the state
# to Running each time the power level changes, and we're already
# in the Running state.

- alias: Set washing machine active when power detected
  trigger:
    - platform: numeric_state
      entity_id: sensor.washing_machine_power
      above: 10
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: sensor.washing_machine_status
        state: Idle
      - condition: state
        entity_id: sensor.washing_machine_status
        state: Clean
      - condition: state
        entity_id: sensor.washing_machine_status
        state: Finishing
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washing_machine_status
        option: Running

# When the power drops, move the state of the washing machine to
# Finishing.

- alias: Set washing machine finished when power drops
  trigger:
    - platform: numeric_state
      entity_id: sensor.washing_machine_power
      below: 6
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.washing_machine_status
        state: Running
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washing_machine_status
        option: Finishing

# Wait 8 minutes for us to be in the Finishing state before we
# decide the washing machine has finished. This way, if the
# washing machine is in between cycles and the power drops, we
# won't mark the washing machine cycle as finished too early.

- alias: Set washing machine clean after timeout
  trigger:
    - platform: state
      entity_id: input_select.washing_machine_status
      to: Finishing
      for:
        minutes: 8
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.washing_machine_status
        state: Finishing
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washing_machine_status
        option: Clean

# When we open the washing machine door, reset the status back to
# idle, so we don't spam people that the washing machine has
# finished, and someone has already emptied it
#- alias: Set washing machine dirty when door opens
#  trigger:
#    # I've setup a template sensor to change make the binary_sensor report open and closed
#    # instead of 1 and 0
#    - platform: state
#      entity_id: input_select.washingmachine_door_status
#      to: 'Open'
#  condition:
#    condition: and
#    conditions:
#      - condition: state
#        entity_id: input_select.washing_machine_status
#        state: Clean
#  action:
#    - service: input_select.select_option
#      data:
#        entity_id: input_select.washing_machine_status
#        option: Idle

- alias: Send alert when washing machine is finished
  trigger:
    - platform: state
      entity_id: sensor.washing_machine_status
      to: Clean
      for:
        minutes: 1
    - platform: state
      entity_id: device_tracker.eamonn
      to: 'home'
      for:
        minutes: 2
    - platform: time
      at: '08:45:00'
  condition:
    condition: and
    conditions:
      - condition: time
        before: '22:30:00'
        after: '08:30:00'
      - condition: state
        entity_id: group.people
        state: 'home'
      - condition: state
        entity_id: input_select.washing_machine_status
        state: Clean
      - condition: template
        value_template: >
          {% if states.automation.send_alert_when_washing_machine_is_finished.last_triggered is not none %}
            {% if as_timestamp(now()) | int   -  as_timestamp(states.automation.send_alert_when_washing_machine_is_finished.attributes.last_triggered) | int > 1800 %} true {% else %} false
            {% endif %}
          {% else %}
          false
          {% endif %}
  action:
    - service_template: >
        {% if is_state('device_tracker.eamonn_s7', 'home') %}
          notify.eamonn_s7
        {% endif %}
      data:
        message: 'Hey, the washing machine has finished and is ready to be emptied'
        title: 'Washing Machine'
